#!/usr/bin/env perl

use JSON;
use Data::Dumper;

use warnings;
use strict;

my $json = JSON->new->allow_nonref;

if ( ! -d $ENV{WIKI_DIR} ) {
	print STDERR "WIKI_DIR environment must be set to valid directory";
	exit 1;
}

my @input = <STDIN>;
my $title = $json->decode( join( "", @input ) );

my $file_name = $ENV{WIKI_DIR} . "/" . $title . ".wiki";

if ( ! ( -e $file_name ) ) {
	die( "file not found; title: \"" . $title . "\"" );
}

my $sha1 = `sha1sum "$file_name" | sed -e "s/ .*//" | tr -d "\n"`;

my $article_version = {
	"title" => $title,
	"hash" => $sha1
};

my $response_json = $json->encode( $article_version );
print $response_json;
print "\n";
