[ "in",
	[ "map", "ArticleSnapshot : String -> Category", "Current" ],
	[ "in",
		[ "map", "HashTableLookup : String -> Category",
			[ "map", "String : Value -> String",
				[ "in",
					[ "map", "HashTableLookup : String -> Category", "Example_Program_Fragment"],
					[ "map", "Lookup : _ -> Value",
						[ "map", "Position : _ -> HashTable",
							[ "map", "SectionTitle : _ -> StringTuple",
								[ "map", "Source : _ -> WikitextDocument",
									[ "map", "Current : ArticleTitle -> ArticleVersion",
										"Litcomp" ] ] ] ] ] ] ] ],
		[ "map", "Lookup : _ -> Value",
			[ "map", "SectionIndex : _ -> HashTable",
				[ "map", "ProgramFragment : _ -> ProgramFragmentTuple",
					[ "map", "Source : _ -> WikitextDocument",
						[ "map", "Current : ArticleTitle -> ArticleVersion",
							"Litcomp" ] ] ] ] ] ] ]
